name: 'Client tests'

on:
  pull_request:
    branches:
      - main
      - dev
    types:
      - opened
      - synchronize
      - edited

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Cache root node_modules
        uses: actions/cache@v3
        id: cache-root-node-modules
        with:
          path: node_modules
          key: root-${{ hashFiles('package.json', 'package-lock.json') }}

      - name: Install dependencies (if not cached)
        if: steps.cache-root-node-modules.outputs.cache-hit != 'true'
        run: npm ci
        env:
          CI: true

      - name: Eslint
        run: npm run eslint

      - name: Stylelint
        run: npm run stylelint
